library(devtools)

install("extractoR.data")
install("extractoR.cran")
install("extractoR.github")
install("extractoR.description")
install("extractoR.namespace")
install("extractoR.extract")
install("extractoR.snapshots")
install("extractoR.content")
install("extractoR")
