library(devtools)

install("extractoR.data")
install("extractoR.mongo")
install("extractoR.cran")
install("extractoR.github")
install("extractoR.extract")
install("extractoR.snapshots")
install("extractoR.content")
install("extractoR")
